### ISSUE TITLE
IllegalArgumentException when IntelliJ IDEA 12 loses focus

### ISSUE THREAD

**Issue by legrego** [omayevskiy/sonar-intellij-plugin#11]
Since upgrading to version 1.3 of the plugin, I get this error in the Event Log when the IDE loses focus: 
`8:26:02 AM IllegalArgumentException: Extension is missing for storage file: Extension is missing for storage file:`

Additionally, an error dialog appears each time saying: `Could not save project: Extension is missing for storage file:`

Here is the stack trace:
`2013-08-08 08:36:25,055 [ 655647]   INFO - ellij.project.impl.ProjectImpl - Error saving project 
java.io.IOException: Extension is missing for storage file: 
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.startSave(ComponentStoreImpl.java:126)
    at com.intellij.openapi.components.impl.stores.ProjectWithModulesStoreImpl.startSave(ProjectWithModulesStoreImpl.java:39)
    at com.intellij.openapi.components.impl.stores.StoreUtil.doSave(StoreUtil.java:30)
    at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:360)
    at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:146)
    at com.intellij.ide.SaveAndSyncHandlerImpl$3.onFrameDeactivated(SaveAndSyncHandlerImpl.java:100)
    at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:100)
    at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:34)
    at com.intellij.ide.FrameStateManagerImpl$2$1.run(FrameStateManagerImpl.java:73)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:289)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:343)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:721)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:691)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.IllegalArgumentException: Extension is missing for storage file: 
    at com.intellij.openapi.components.impl.stores.StateStorageManagerImpl.b(StateStorageManagerImpl.java:231)
    at com.intellij.openapi.components.impl.stores.StateStorageManagerImpl.a(StateStorageManagerImpl.java:176)
    at com.intellij.openapi.components.impl.stores.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.java:109)
    at com.intellij.openapi.components.impl.stores.StateStorageManagerImpl$MyExternalizationSession.setState(StateStorageManagerImpl.java:456)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.a(ComponentStoreImpl.java:155)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.access$600(ComponentStoreImpl.java:44)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl$SaveSessionImpl.commit(ComponentStoreImpl.java:484)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.startSave(ComponentStoreImpl.java:110)
    ... 27 more`

Note: disabling the plugin resolves the errors, so I am fairly convinced it is related to the latest update.

**Comment by mplushnikov** [comment]
Should be fixed in 1.3.1
