### ISSUE TITLE
Getting NullPointerException on webstorm 6.0.2 with sonar-3.6.2 [File -> Default Settings... -> Sonar-connector]

### ISSUE THREAD

**Issue by amitdh** [omayevskiy/sonar-intellij-plugin#9]
I am not able to configure/use the plugin.

The issues I observed are:-
1. Test connection in settings is behaving inconsistently. It says "connection not successful" and sometimes "Connection successfull Sonar v.null" as shown in the image below:-
![image](https://f.cloud.github.com/assets/4748167/916163/c946eca6-fe83-11e2-96b6-9216e1890dad.png)
1. Also, when I do [File -> Default Settings... -> Sonar-connector], NPE is thrown as shown below and "Loading..." status is shown in the IDE, forever.
   ![plugin-configure-error-sonar-3 6 2](https://f.cloud.github.com/assets/4748167/916127/2698e338-fe83-11e2-9dd3-507665b340b1.png)
2. Also, if i perform "sync with sonar" from a opened file (using right click), nothing happens.

**Comment by amitdh** [comment]
After upgrading the Plugin, Project Setting > Sonar Connector > Test connection is working OK.

But, NPE persists on File > Default Settings...
Stack Trace:-
null
java.lang.NullPointerException
    at org.mayevskiy.intellij.sonar.SonarSettingsConfigurable.createComponent(SonarSettingsConfigurable.java:82)
    at com.intellij.openapi.options.newEditor.OptionsEditor$Simple.<init>(OptionsEditor.java:1270)
    at com.intellij.openapi.options.newEditor.OptionsEditor.b(OptionsEditor.java:455)
    at com.intellij.openapi.options.newEditor.OptionsEditor.access$2500(OptionsEditor.java:68)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1$1.run(OptionsEditor.java:424)
    at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1130)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9$1.run(OptionsEditor.java:418)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:940)
    at com.intellij.openapi.options.newEditor.OptionsEditor$9.run(OptionsEditor.java:416)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)
